name: Deploy MyST Docs to GitHub Pages

on:
  push:
    branches: ["readme"] 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MyST CLI
        run: |
          npm install -g mystmd

      - name: Build MyST site
        run: |
          myst build  # Builds the static site into ./_build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html  # MyST outputs HTML here

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
